name: Tagged release deploy

on:
  workflow_dispatch:
    inputs:
      changelist:
        description: 'patch and pre-release metadata'
        required: true
        default: '.0-alpha.1'


jobs:
  build:
    runs-on: ubuntu-20.04

    # Should only release tags
    # TODO: should only release tags where the required status checks are passing
    if: startsWith(github.ref, ‘refs/tags/’)

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v3
      # Step that does that actual cache save and restore
      - uses: actions/cache@v3.2.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
           ${{ runner.os }}-maven-

      - name: Store Maven project version 
        run: echo "maven_project_version=$(mvn help:evaluate -Dexpression=project.version -Dchangelist=${{ github.event.inputs.changelist }} -q -DforceStdout)" >> $GITHUB_ENV

      - name: Read exported variable
        run: |
          echo "${{ env.maven_project_version }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: docker_checksum_upload_from_github
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy with mvnw
        run: |
         git config --global user.email "${{ github.actor }}"
         git config --global user.name "${{ github.actor }}"
         ./mvnw --batch-mode deploy -ntp -s .github/collab-mvn-settings.xml -DskipTests -Dchangelist=${{ github.event.inputs.changelist }}
        env: 
          COLLAB_DEPLOY_TOKEN: ${{ secrets.COLLAB_DEPLOY_TOKEN }}

      # neat, quay itself uses manual github actions https://github.com/quay/quay/blob/master/.github/workflows/build-and-publish.yaml
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: quay.io/dockstore/dockstore-webservice:${{ env.maven_project_version }}

      - name: Create checksums
        run: |
          docker inspect quay.io/dockstore/dockstore-webservice:${{ env.maven_project_version }} | grep -A 1 RepoDigests
          docker inspect quay.io/dockstore/dockstore-webservice:${{ env.maven_project_version }} | grep -A 1 RepoDigests | grep -oPm1 'sha256:\K\w+' > image-digest.txt        

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"

      - name: Copy checksum files
        run: aws s3 cp image-digest.txt  s3://${{ secrets.AWS_BUCKET }}/${{ env.maven_project_version }}-${{ steps.slug.outputs.sha7 }}/image-digest.txt
